# Generated by Django 4.1.5 on 2023-01-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translations',
            new_name='Translation',
        ),
    ]
