# Generated by Django 4.1.5 on 2023-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="displayName",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
    ]
